---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-broker-sa
  namespace: brokers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: brokers
  name: efs-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "get", "create", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-rolebinding
  namespace: brokers
subjects:
- kind: ServiceAccount
  name: efs-broker-sa
  namespace: brokers
roleRef:
  kind: Role
  name: efs-role
  apiGroup: rbac.authorization.k8s.io